main: nl.dantevg.afkscoreboard.Main
name: AFKScoreboard
version: 1.0.2
api-version: 1.13
description: Puts the player's AFK status into a scoreboard objective
author: RedPolygon
website: dantevg.nl/mods-plugins/AFKScoreboard
depend: [Essentials]
